language: csharp
solution: StingyBot.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - ls
  - mono nuget.exe restore StingyBot.sln -Verbosity Detailed -NonInteractive -ConfigFile nuget.config
#script: mono msbuild /p:Configuration=Release StingyJunk.sln